# =============================================================================
# Cross-Language Bot Detection Comparison
# English (enwiki) · Russian (ruwiki) · Swedish (svwiki)
# =============================================================================
# Goal: Run a unified bot-detection pipeline across three Wikipedia language
# editions in a single script, then compare:
#   A. Model performance metrics side-by-side
#   B. Bot prevalence and edit-volume differences
#   C. Which edit-type features are universally vs. language-specifically
#      predictive of bot behaviour
#   D. Comment feature signal strength per language
#   E. Cross-language transfer: how well does a model trained on English
#      generalise to Russian and Swedish without retraining?
#
# Each language is processed through an identical pipeline (helpers below),
# producing a standardised results list that feeds all comparison analyses.
#
# MODEL: Elastic-net logistic regression (alpha = 0.5), user-level 80/20
# stratified split, inverse-frequency class weights, 5-fold CV on AUC.
# =============================================================================

# --- Required libraries (loaded once) ----------------------------------------
library(tidyverse)   # Data wrangling & plotting
library(jsonlite)    # Parsing JSON blobs stored in each edit record
library(glmnet)      # Elastic-net penalised logistic regression
library(lubridate)   # Timestamp parsing for temporal features
library(ggrepel)     # Non-overlapping labels on scatter plots

setwd("")

# Convenience null-coalescing operator (used inside extract_features)
`%||%` <- function(a, b) if (!is.null(a)) a else b


# =============================================================================
# SHARED HELPERS
# =============================================================================

# -----------------------------------------------------------------------------
# extract_features()
#
# Parses one edit's JSON blob into a flat named list of numeric counts:
#   - One counter per (node_type × action) pair from "node-edits"
#     e.g. "mwTemplate_insert", "mwHeading_remove"
#   - Total words inserted / removed from "text-edits"
#   - Total number of node-edits and text-edits
#
# Returns NULL on malformed JSON so map() can skip broken rows gracefully.
# -----------------------------------------------------------------------------
extract_features <- function(json_str) {
  parsed <- tryCatch(fromJSON(json_str, simplifyVector = FALSE),
                     error = function(e) NULL)
  if (is.null(parsed)) return(NULL)
  
  # Count each (node_type, action) pair — e.g. 3 template insertions → 3
  node_feats <- list()
  for (ne in parsed[["node-edits"]]) {
    key <- paste0(ne[[1]], "_", ne[[2]])
    node_feats[[key]] <- (node_feats[[key]] %||% 0) + 1
  }
  
  # Sum inserted and removed word counts separately across all text-edits
  n_word_insert <- 0L
  n_word_remove <- 0L
  for (te in parsed[["text-edits"]]) {
    if (te[[2]] == "insert") n_word_insert <- n_word_insert + as.integer(te[[4]])
    if (te[[2]] == "remove") n_word_remove <- n_word_remove + as.integer(te[[4]])
  }
  
  c(node_feats,
    list(n_word_insert = n_word_insert,
         n_word_remove = n_word_remove,
         n_node_edits  = length(parsed[["node-edits"]]),
         n_text_edits  = length(parsed[["text-edits"]])))
}


# -----------------------------------------------------------------------------
# make_comment_features()
#
# Derives binary and numeric features from the free-text revision comment
# that editors leave when saving an edit. These are language-agnostic keyword
# patterns; language-specific terms (e.g. Cyrillic "бот") would need to be
# added per edition if required.
#
# Returns a data frame with one row per edit (same order as input).
# -----------------------------------------------------------------------------
make_comment_features <- function(dat) {
  dat %>%
    mutate(
      # Numeric: raw length and word count
      comment_length      = nchar(revision_comment),
      comment_is_empty    = as.integer(is.na(revision_comment) | revision_comment == ""),
      comment_nwords      = str_count(revision_comment, "\\S+"),
      
      # Bots often self-identify or describe their tooling in comments
      mentions_bot        = as.integer(str_detect(tolower(revision_comment), "bot")),
      mentions_automated  = as.integer(str_detect(tolower(revision_comment),
                                                  "automated|script|auto")),
      
      # Structural comment patterns common in bot comments
      has_wikilink        = as.integer(str_detect(revision_comment, "\\[\\[")),
      starts_with_bracket = as.integer(str_detect(revision_comment, "^\\[")),
      
      # /* Section */ prefix is generated by clicking "edit section" — human only
      starts_with_slash   = as.integer(str_detect(revision_comment, "^/")),
      
      # Semantic content of the comment
      mentions_fix        = as.integer(str_detect(tolower(revision_comment),
                                                  "fix|correct|clean")),
      mentions_revert     = as.integer(str_detect(tolower(revision_comment),
                                                  "revert|undo|rv\\b")),
      
      # Informal punctuation signals human writing
      has_punctuation     = as.integer(str_detect(revision_comment, "[!?]"))
    ) %>%
    select(starts_with("comment_"), starts_with("mentions_"),
           starts_with("starts_with_"), starts_with("has_"))
}


# -----------------------------------------------------------------------------
# run_pipeline()
#
# End-to-end pipeline for one language edition:
#   1. Load up to n_rows edits from a gzip-compressed JSON file
#   2. Extract edit-type features and comment features
#   3. Perform a user-level stratified 80/20 train/test split
#   4. Fit an elastic-net logistic regression with class-imbalance weights
#   5. Evaluate and return a standardised results list
#
# Arguments:
#   file       — path to the .json.gz file
#   n_rows     — maximum number of rows to read (use fewer for quick tests)
#   lang_label — human-readable label used in plots and tables
#
# Returns a named list with: data, combined features, metrics, coefficients,
# feature signal ratios, fitted model, and feature column names.
# Returns NULL if there are too few bot users to split.
# -----------------------------------------------------------------------------
run_pipeline <- function(file, n_rows, lang_label) {
  cat("\n====================================================\n")
  cat(" Processing:", lang_label, "\n")
  cat("====================================================\n")
  
  # --- 1. Load data ----------------------------------------------------------
  con <- textConnection(readLines(gzfile(file), n = n_rows))
  dat <- stream_in(con, verbose = FALSE)
  close(con)
  cat("Rows loaded:", nrow(dat),
      "| Bot share:", round(mean(dat$is_bot) * 100, 1), "%\n")
  
  # --- 2a. Edit-type features -----------------------------------------------
  # map() applies extract_features() to every JSON string, then bind_rows()
  # stacks the results. Spaces in column names are replaced with underscores
  # so glmnet does not choke on them.
  edit_feats <- dat$edit_types_json %>%
    map(extract_features) %>%
    map(as_tibble) %>%
    bind_rows(.id = "row_id") %>%
    mutate(
      across(everything(), ~ replace_na(.x, 0)),   # Missing counts → 0
      row_id    = as.integer(row_id),
      is_bot    = as.integer(dat$is_bot[row_id]),
      page_id   = dat$page_id[row_id],
      user_text = dat$user_text[row_id]
    ) %>%
    rename_with(~ str_replace_all(., " ", "_"))
  
  # --- 2b. Comment features -------------------------------------------------
  comm_feats <- make_comment_features(dat)
  
  # --- 2c. Combine into one feature matrix ----------------------------------
  combined  <- bind_cols(edit_feats, comm_feats)
  feat_cols <- combined %>%
    select(-row_id, -is_bot, -page_id, -user_text) %>%
    names()
  
  # --- 3. User-level stratified 80/20 split ---------------------------------
  # Each user's edits are kept entirely in either train or test.
  # If a user has any bot-labelled edit, they are treated as a bot user.
  user_labels <- combined %>%
    group_by(user_text) %>%
    summarise(is_bot = max(is_bot), .groups = "drop")
  
  set.seed(42)
  bot_u   <- user_labels %>% filter(is_bot == 1) %>% pull(user_text)
  human_u <- user_labels %>% filter(is_bot == 0) %>% pull(user_text)
  
  # Guard: at least 2 bot users are needed for a meaningful stratified split
  if (length(bot_u) < 2) {
    cat("  Too few bot users — skipping model fit.\n")
    return(NULL)
  }
  
  train_users <- c(sample(bot_u,   size = max(1, floor(0.8 * length(bot_u)))),
                   sample(human_u, size = floor(0.8 * length(human_u))))
  
  tr_idx <- which( combined$user_text %in% train_users)
  te_idx <- which(!combined$user_text %in% train_users)
  
  train <- combined[tr_idx, ]
  test  <- combined[te_idx, ]
  
  # --- 4. Class-imbalance weights -------------------------------------------
  # Rare bot class is upweighted so it contributes equally to the loss.
  n_tr <- nrow(train)
  n_b  <- sum(train$is_bot)
  w_tr <- ifelse(train$is_bot == 1,
                 n_tr / (2 * n_b),
                 n_tr / (2 * (n_tr - n_b)))
  
  X_tr <- train %>% select(all_of(feat_cols)) %>% as.matrix()
  X_te <- test  %>% select(all_of(feat_cols)) %>% as.matrix()
  y_tr <- train$is_bot
  
  # --- 5. Elastic-net (5-fold CV, optimise AUC) -----------------------------
  set.seed(42)
  cv_m <- cv.glmnet(X_tr, y_tr,
                    family       = "binomial",   # Logistic regression
                    alpha        = 0.5,           # 50% L1 + 50% L2
                    weights      = w_tr,
                    nfolds       = 5,
                    type.measure = "auc")
  
  # Predict at lambda that maximises CV-AUC; threshold at 0.5
  prob <- predict(cv_m, newx = X_te, s = "lambda.min", type = "response")[, 1]
  pred <- as.integer(prob > 0.5)
  y_te <- test$is_bot
  
  # Confusion matrix counts
  tp <- sum(pred == 1 & y_te == 1)   # Correct bot predictions
  fp <- sum(pred == 1 & y_te == 0)   # Humans wrongly flagged as bots
  fn <- sum(pred == 0 & y_te == 1)   # Bots the model missed
  tn <- sum(pred == 0 & y_te == 0)   # Correct human predictions
  
  # --- 6. Compile outputs ---------------------------------------------------
  
  # Scalar performance metrics
  metrics <- tibble(
    language  = lang_label,
    n_edits   = nrow(dat),
    bot_share = round(mean(dat$is_bot) * 100, 1),
    n_users   = nrow(user_labels),
    n_bots    = sum(user_labels$is_bot),
    auc_cv    = round(max(cv_m$cvm), 3),
    precision = round(tp / (tp + fp), 3),    # Of predicted bots, how many are real?
    recall    = round(tp / (tp + fn), 3),    # Of all real bots, how many did we catch?
    f1        = round(2 * tp / (2 * tp + fp + fn), 3),   # Harmonic mean
    accuracy  = round((tp + tn) / (tp + tn + fp + fn), 3)
  )
  
  # Non-zero model coefficients (positive = bot signal, negative = human signal)
  cm    <- coef(cv_m, s = "lambda.min")
  coefs <- tibble(
    language = lang_label,
    term     = rownames(cm),
    estimate = as.numeric(cm)
  ) %>%
    filter(term != "(Intercept)")
  
  # Log2(bot mean / human mean) for every feature — used in EDA plots
  mean_ratio <- combined %>%
    group_by(is_bot) %>%
    summarise(across(all_of(feat_cols), mean), .groups = "drop") %>%
    pivot_longer(-is_bot, names_to = "feature", values_to = "mean_val") %>%
    pivot_wider(names_from = is_bot, values_from = mean_val,
                names_prefix = "bot_") %>%
    rename(human = bot_0, bot = bot_1) %>%
    mutate(
      language  = lang_label,
      log2ratio = log2((bot + 0.001) / (human + 0.001))   # +0.001 avoids log(0)
    )
  
  list(
    data      = dat,
    combined  = combined,
    metrics   = metrics,
    coefs     = coefs,
    ratios    = mean_ratio,
    model     = cv_m,
    feat_cols = feat_cols
  )
}


# =============================================================================
# 1. RUN PIPELINE FOR ALL THREE LANGUAGES
# =============================================================================
# n_rows can be reduced for quicker iteration during development.
# Swedish has fewer edits in the dataset so 5,000 rows is used there.

results <- list(
  english = run_pipeline("enwiki.json.gz", n_rows = 10000, lang_label = "English"),
  russian = run_pipeline("ruwiki.json.gz", n_rows = 10000, lang_label = "Russian"),
  swedish = run_pipeline("svwiki.json.gz", n_rows = 5000,  lang_label = "Swedish")
)

# Drop any language that returned NULL (too few bot users to model)
results <- Filter(Negate(is.null), results)

cat("\nLanguages successfully processed:", paste(names(results), collapse = ", "), "\n")


# =============================================================================
# 2. SIDE-BY-SIDE METRICS TABLE
#
# Collects the scalar metrics from every language into one tidy data frame,
# then prints and plots them for easy comparison.
# =============================================================================

metrics_all <- map_dfr(results, "metrics")

cat("\n================================================================\n")
cat("        PERFORMANCE COMPARISON — ALL THREE LANGUAGES\n")
cat("================================================================\n")
print(metrics_all)

# Reshape to long format for faceted bar chart
metrics_long <- metrics_all %>%
  select(language, auc_cv, precision, recall, f1) %>%
  pivot_longer(-language, names_to = "metric", values_to = "value") %>%
  mutate(metric = factor(metric,
                         levels = c("auc_cv", "precision", "recall", "f1"),
                         labels = c("AUC (CV)", "Precision", "Recall", "F1")))

ggplot(metrics_long, aes(x = language, y = value, fill = language)) +
  geom_col(width = 0.6, alpha = 0.92) +
  geom_text(aes(label = sprintf("%.3f", value)), vjust = -0.4, size = 3.2) +
  facet_wrap(~ metric, nrow = 1) +
  scale_fill_manual(values = c("English" = "steelblue",
                               "Russian" = "tomato",
                               "Swedish" = "forestgreen")) +
  scale_y_continuous(limits = c(0, 1.08),
                     expand = expansion(mult = c(0, 0))) +
  labs(title = "Bot detection model performance by language",
       x = NULL, y = NULL, fill = NULL) +
  theme_minimal(base_size = 12) +
  theme(legend.position = "none",
        strip.text      = element_text(face = "bold"),
        panel.grid.major.x = element_blank())


# =============================================================================
# 3. BOT PREVALENCE & DATASET CHARACTERISTICS
#
# Class imbalance directly affects how hard detection is. An edition where
# 20% of edits are bots provides more training signal than one with 4%.
# =============================================================================

ggplot(metrics_all, aes(x = language, y = bot_share, fill = language)) +
  geom_col(width = 0.5, alpha = 0.92) +
  geom_text(aes(label = paste0(bot_share, "%")), vjust = -0.4, size = 4) +
  scale_fill_manual(values = c("English" = "steelblue",
                               "Russian" = "tomato",
                               "Swedish" = "forestgreen")) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +
  labs(title = "Bot edit share by language edition",
       x = NULL, y = "% of edits by bots") +
  theme_minimal(base_size = 12) +
  theme(legend.position    = "none",
        panel.grid.major.x = element_blank())


# =============================================================================
# 4. FEATURE SIGNAL COMPARISON (log2 bot/human ratio)
#
# Combines the bot/human mean ratios from all three editions to show which
# edit-type features are universally diagnostic and which are
# language-specific. Displaying only the 25 features with the strongest
# signal in at least one edition keeps the plot readable.
# =============================================================================

ratios_all <- map_dfr(results, "ratios")

# Keep only the 25 features with the highest absolute signal in any edition
top_features <- ratios_all %>%
  group_by(feature) %>%
  summarise(max_abs = max(abs(log2ratio)), .groups = "drop") %>%
  slice_max(max_abs, n = 25) %>%
  pull(feature)

ratios_all %>%
  filter(feature %in% top_features) %>%
  # Order features by their maximum absolute signal across all editions
  mutate(feature = fct_reorder(feature, log2ratio,
                               .fun = function(x) max(abs(x)))) %>%
  ggplot(aes(x = log2ratio, y = feature, fill = language)) +
  geom_col(position = "dodge") +
  geom_vline(xintercept = 0, colour = "grey40") +
  scale_fill_manual(values = c("English" = "steelblue",
                               "Russian" = "tomato",
                               "Swedish" = "forestgreen")) +
  labs(title    = "Edit-type feature signal: bot vs. human (log2 ratio)",
       subtitle = "Positive = bot-skewed  |  Negative = human-skewed",
       x        = "log2(bot mean / human mean)",
       y        = NULL,
       fill     = "Language") +
  theme_minimal(base_size = 11)


# =============================================================================
# 5. COEFFICIENT COMPARISON ACROSS LANGUAGES
#
# Extracts the elastic-net coefficients retained by each language's model
# and visualises them in two ways:
#   (a) Heatmap of the 30 features with the largest absolute coefficient in
#       any single edition — shows which features matter most overall
#   (b) Table of features retained in ALL three editions — the most robust
#       cross-lingual predictors
# =============================================================================

coefs_all <- map_dfr(results, "coefs")

# Pivot to wide so each language has its own coefficient column.
# Features absent from a language's model are filled with 0 (shrunk to zero
# by regularisation, meaning the model found them uninformative).
coefs_wide <- coefs_all %>%
  filter(estimate != 0) %>%
  pivot_wider(names_from  = language,
              values_from = estimate,
              values_fill = 0) %>%
  filter(term != "(Intercept)")

# Identify the language columns present in this run
lang_cols <- map_chr(results, ~ .x$metrics$language)

# Features with a non-zero coefficient in every language = most robust signals.
# rowSums() / rowMeans() operate on a plain submatrix, avoiding the c_across()
# scoping issue that occurs inside rowwise() when column names come from an
# external character vector.
universal <- coefs_wide %>%
  mutate(
    n_nonzero = rowSums(across(all_of(lang_cols)) != 0),
    mean_abs  = rowMeans(abs(across(all_of(lang_cols))))
  ) %>%
  filter(n_nonzero == length(lang_cols)) %>%
  arrange(desc(mean_abs)) %>%
  select(-n_nonzero, -mean_abs)

cat("\n=== Features with non-zero coefficients in ALL languages ===\n")
print(universal, n = 20)

# --- Heatmap of top-30 features by absolute coefficient ---------------------
top_terms <- coefs_all %>%
  group_by(term) %>%
  summarise(max_abs = max(abs(estimate)), .groups = "drop") %>%
  filter(term != "(Intercept)") %>%
  slice_max(max_abs, n = 30) %>%
  pull(term)

coefs_all %>%
  filter(term %in% top_terms) %>%
  ggplot(aes(x    = language,
             y    = fct_reorder(term, abs(estimate)),
             fill = estimate)) +
  geom_tile(colour = "white", linewidth = 0.4) +
  scale_fill_gradient2(low      = "steelblue",
                       mid      = "white",
                       high     = "tomato",
                       midpoint = 0) +
  labs(title    = "Elastic net coefficients: top 30 features across languages",
       subtitle = "Red = bot signal  |  Blue = human signal  |  White = shrunk to zero",
       x = NULL, y = NULL, fill = "Coefficient") +
  theme_minimal(base_size = 11) +
  theme(axis.text.x = element_text(face = "bold", size = 11),
        axis.text.y = element_text(size = 8),
        panel.grid  = element_blank())


# =============================================================================
# 6. PAIRWISE COEFFICIENT SCATTER PLOTS
#
# Plotting one language's coefficients against another's shows:
#   - Points near the diagonal: both models agree on direction AND magnitude
#   - Points in Q1 or Q3 (same sign): consistent direction, different strength
#   - Points in Q2 or Q4 (opposite sign): the feature predicts opposite things
#     in different editions — a sign of language-specific behaviour
# =============================================================================

make_pair_scatter <- function(lang_a, lang_b, df_wide) {
  # Guard: both languages must be present in the data
  if (!all(c(lang_a, lang_b) %in% names(df_wide))) return(NULL)
  
  df_wide %>%
    ggplot(aes(x = .data[[lang_a]], y = .data[[lang_b]], label = term)) +
    geom_hline(yintercept = 0, linetype = "dashed", colour = "grey70") +
    geom_vline(xintercept = 0, linetype = "dashed", colour = "grey70") +
    # Dotted diagonal = features with identical coefficient in both languages
    geom_abline(slope = 1, intercept = 0, linetype = "dotted", colour = "grey50") +
    # Colour by whether the two models agree on direction (sign)
    geom_point(aes(colour = sign(.data[[lang_a]]) == sign(.data[[lang_b]])),
               size = 2.5, alpha = 0.8) +
    geom_text_repel(size = 2.8, max.overlaps = 12) +
    scale_colour_manual(
      values = c("TRUE" = "tomato", "FALSE" = "steelblue"),
      labels = c("TRUE" = "Same direction", "FALSE" = "Opposite direction")
    ) +
    labs(title    = paste("Coefficients:", lang_a, "vs.", lang_b),
         subtitle = "Points on dotted diagonal = identical signal strength",
         x        = paste0("Coefficient (", lang_a, ")"),
         y        = paste0("Coefficient (", lang_b, ")"),
         colour   = NULL) +
    theme_minimal(base_size = 12)
}

make_pair_scatter("English", "Russian", coefs_wide)
make_pair_scatter("English", "Swedish", coefs_wide)
make_pair_scatter("Russian", "Swedish", coefs_wide)


# =============================================================================
# 7. COMMENT FEATURE SIGNAL BY LANGUAGE
#
# Comment patterns may vary significantly across editions — for example,
# Russian bots may self-identify using Cyrillic "бот" rather than "bot"
# (the make_comment_features() helper only checks "bot" in Latin script,
# so the Russian mentions_bot signal may be underestimated here).
# =============================================================================

comment_feat_names <- c(
  "comment_is_empty", "comment_nwords",
  "mentions_bot", "mentions_automated", "mentions_fix", "mentions_revert",
  "has_wikilink", "starts_with_bracket", "starts_with_slash", "has_punctuation"
)

# Compute log2 bot/human ratio for every comment feature in each edition
comment_ratios <- map_dfr(results, function(res) {
  lang <- res$metrics$language
  res$combined %>%
    group_by(is_bot) %>%
    summarise(across(any_of(comment_feat_names), mean, na.rm = TRUE),
              .groups = "drop") %>%
    pivot_longer(-is_bot, names_to = "feature", values_to = "mean_val") %>%
    pivot_wider(names_from  = is_bot,
                values_from = mean_val,
                names_prefix = "bot_") %>%
    rename(human = bot_0, bot = bot_1) %>%
    mutate(language  = lang,
           log2ratio = log2((bot + 0.001) / (human + 0.001)))
})

ggplot(comment_ratios,
       aes(x = log2ratio,
           y = fct_reorder(feature, abs(log2ratio)),
           fill = language)) +
  geom_col(position = "dodge") +
  geom_vline(xintercept = 0, colour = "grey40") +
  scale_fill_manual(values = c("English" = "steelblue",
                               "Russian" = "tomato",
                               "Swedish" = "forestgreen")) +
  labs(title    = "Comment feature signal by language (log2 bot/human ratio)",
       subtitle = "Positive = bot-skewed  |  Negative = human-skewed",
       x = "log2(bot mean / human mean)", y = NULL, fill = "Language") +
  theme_minimal(base_size = 11)


# =============================================================================
# 8. CROSS-LANGUAGE TRANSFER TEST
#
# Trains on English and evaluates directly on Russian and Swedish WITHOUT
# retraining. This answers: "Do the patterns learned from English bots
# generalise to other languages, or is bot behaviour edition-specific?"
#
# To align feature spaces, missing columns are added as zero-filled columns.
# A large gap between transfer F1 and native F1 indicates that bot behaviour
# in that language has unique signals not present in English training data.
# =============================================================================

transfer_results <- tibble()

eng_res <- results[["english"]]
if (!is.null(eng_res)) {
  
  for (lang_key in setdiff(names(results), "english")) {
    tgt     <- results[[lang_key]]
    tgt_lab <- tgt$metrics$language
    
    # Align target feature matrix to the English feature set:
    # add any columns the target is missing (with zeros) and reorder to match
    tgt_X <- tgt$combined %>%
      select(any_of(eng_res$feat_cols)) %>%
      {
        missing_cols <- setdiff(eng_res$feat_cols, names(.))
        for (mc in missing_cols) .[[mc]] <- 0L   # Feature unseen in this edition → 0
        .
      } %>%
      select(all_of(eng_res$feat_cols)) %>%
      as.matrix()
    
    tgt_X[is.na(tgt_X)] <- 0   # Residual NAs → 0
    
    # Apply the English model to the target language's edits
    prob_t <- predict(eng_res$model, newx = tgt_X,
                      s = "lambda.min", type = "response")[, 1]
    pred_t <- as.integer(prob_t > 0.5)
    y_t    <- as.integer(tgt$combined$is_bot)
    
    tp_t <- sum(pred_t == 1 & y_t == 1)
    fp_t <- sum(pred_t == 1 & y_t == 0)
    fn_t <- sum(pred_t == 0 & y_t == 1)
    
    transfer_results <- bind_rows(transfer_results, tibble(
      target      = tgt_lab,
      f1_transfer = round(2 * tp_t / (2 * tp_t + fp_t + fn_t), 3),
      f1_native   = tgt$metrics$f1
    ))
  }
}

cat("\n=== Cross-language transfer vs. native model ===\n")
print(transfer_results)

# Bar chart: transfer F1 vs. native F1 per target language
if (nrow(transfer_results) > 0) {
  transfer_results %>%
    pivot_longer(cols      = c(f1_transfer, f1_native),
                 names_to  = "model_type",
                 values_to = "f1") %>%
    mutate(model_type = recode(model_type,
                               f1_transfer = "English-trained model",
                               f1_native   = "Language-native model")) %>%
    ggplot(aes(x = target, y = f1, fill = model_type)) +
    geom_col(position = "dodge", width = 0.5, alpha = 0.92) +
    geom_text(aes(label = sprintf("%.3f", f1)),
              position = position_dodge(width = 0.5),
              vjust = -0.4, size = 3.5) +
    scale_fill_manual(values = c("English-trained model" = "steelblue",
                                 "Language-native model" = "tomato")) +
    scale_y_continuous(limits = c(0, 1.1),
                       expand = expansion(mult = c(0, 0))) +
    labs(title    = "Cross-language transfer: English-trained vs. native model",
         subtitle = "A small gap = bot behaviour generalises across languages",
         x = NULL, y = "F1 score", fill = NULL) +
    theme_minimal(base_size = 12) +
    theme(panel.grid.major.x = element_blank(),
          legend.position    = "bottom")
}

cat("\nDone — all plots rendered.\n")

